### ISSUE TITLE
format_bnc.py crashes [line32]

### ISSUE THREAD

**Issue by stefanobellelli** [stefanobellelli/nonce3vec#2]
Maybe because it stumbles upon an empty line, so `lemmas()` has nothing to choose from?
```
Traceback (most recent call last):
  File "format_bnc.py", line 32, in <module>
    lemmalist = lemmas(sentencelist)
  File "/home/stefano/nonce3vec/lib.py", line 26, in lemmas
    lemma = random.choice(line.split())
  File "/usr/lib/python3.6/random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by stefanobellelli** [comment]
I have added a control `while` to replace faulty lines. Now it works.
